apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: test-alert2
  namespace: monitoring

  labels:
    release: stable

spec:
  groups:
  - name: test-alert-group-2

    rules:
    - alert: TestAlert2

      expr: vector(1)

      for: 1m

      labels:
        severity: warning

      annotations:
        summary: Test Alert2

        description: Testing Alertmanager Integration