apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring-stack
  namespace: argocd

spec:
  project: default

  sources:

    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 86.2.2

      helm:
        valueFiles:
          - $values/Alert-Monitoring/monitoring-stack/values.yaml

    - repoURL: https://github.com/pranav0015/Zomato-App-Deploy-Complete-CICD.git
      targetRevision: HEAD
      ref: values #this value.yaml file will be provided to HELM valueFiles as an input

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true