apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-alert
  namespace: prometheus
  labels:
    release: monitoring-stack # from  stable-kube-prometheus-sta-prometheus "ruleNamespaceSelector" field
    app.kubernetes.io/instance: monitoring-infrastructure # from argocd yaml
spec:
  groups:
  - name: node-alert
    rules:
    - alert: HighCPUUsage
      expr: |-
        (
          100 -
          (
            avg by(instance)
            (
              rate(node_cpu_seconds_total{mode='idle'}[5m])
            ) * 100
          )    
        ) > 80

      for: 2m
      labels:
        severity: critical
      annotations:
        summary: High CPU Usage
        description: CPU utilization exceeds 80%
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/cputhrottlinghigh/

    