apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: slack-test
  namespace: prometheus
  labels:
    release: monitoring-stack
spec:
  groups:
  - name: test
    rules:
    - alert: SlackTemplateTest
      expr: vector(1)
      for: 1m
      labels:
        severity: critical
      annotations:
        description: Testing Slack template